/*
  Warnings:

  - You are about to drop the column `branch_mentor_name` on the `profiles` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "profiles" DROP COLUMN "branch_mentor_name",
ADD COLUMN     "academic_level" TEXT,
ADD COLUMN     "alt_number" TEXT,
ADD COLUMN     "backlogs" JSONB,
ADD COLUMN     "batch" TEXT DEFAULT '2022 - 2026',
ADD COLUMN     "branch_mentor" TEXT,
ADD COLUMN     "calling_number" TEXT,
ADD COLUMN     "category" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "current_area" TEXT,
ADD COLUMN     "current_cross" TEXT,
ADD COLUMN     "current_district" TEXT,
ADD COLUMN     "current_house" TEXT,
ADD COLUMN     "diploma_area" TEXT,
ADD COLUMN     "diploma_certificates" TEXT,
ADD COLUMN     "diploma_city" TEXT,
ADD COLUMN     "diploma_college" TEXT,
ADD COLUMN     "diploma_district" TEXT,
ADD COLUMN     "diploma_first_year" TEXT,
ADD COLUMN     "diploma_second_year" TEXT,
ADD COLUMN     "diploma_semesters" JSONB,
ADD COLUMN     "diploma_third_year" TEXT,
ADD COLUMN     "district" TEXT DEFAULT 'DHARWAD',
ADD COLUMN     "dob_day" TEXT,
ADD COLUMN     "dob_month" TEXT,
ADD COLUMN     "dob_year" TEXT,
ADD COLUMN     "father_first_name" TEXT,
ADD COLUMN     "father_last_name" TEXT,
ADD COLUMN     "father_middle_name" TEXT,
ADD COLUMN     "github_link" TEXT,
ADD COLUMN     "has_backlogs" TEXT,
ADD COLUMN     "hostel_floor" TEXT,
ADD COLUMN     "hostel_room" TEXT,
ADD COLUMN     "leetcode_link" TEXT,
ADD COLUMN     "linkedin_link" TEXT,
ADD COLUMN     "mother_first_name" TEXT,
ADD COLUMN     "mother_last_name" TEXT,
ADD COLUMN     "mother_middle_name" TEXT,
ADD COLUMN     "permanent_area" TEXT,
ADD COLUMN     "permanent_cross" TEXT,
ADD COLUMN     "permanent_district" TEXT,
ADD COLUMN     "permanent_house" TEXT,
ADD COLUMN     "pincode" TEXT DEFAULT '580002',
ADD COLUMN     "resume_upload" TEXT,
ADD COLUMN     "semesters" JSONB,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "student_email" TEXT,
ADD COLUMN     "tenth_area" TEXT,
ADD COLUMN     "tenth_city" TEXT,
ADD COLUMN     "tenth_district" TEXT,
ADD COLUMN     "tenth_school" TEXT,
ADD COLUMN     "twelfth_area" TEXT,
ADD COLUMN     "twelfth_cbse_marks" TEXT,
ADD COLUMN     "twelfth_cbse_subjects" TEXT,
ADD COLUMN     "twelfth_city" TEXT,
ADD COLUMN     "twelfth_district" TEXT,
ADD COLUMN     "twelfth_icse_marks" TEXT,
ADD COLUMN     "twelfth_school" TEXT,
ADD COLUMN     "whatsapp_number" TEXT,
ALTER COLUMN "college_name" SET DEFAULT 'SHRI DHARMASTHALA MANJUNATHESHWARA COLLEGE OF ENGINEERING AND TECHNOLOGY',
ALTER COLUMN "tenth_passing_month" SET DATA TYPE TEXT,
ALTER COLUMN "twelfth_passing_month" SET DATA TYPE TEXT;
