// Indian States and Major Cities Data for Professional Forms

export const INDIAN_STATES = [
  "ANDHRA PRADESH", "ARUNACHAL PRADESH", "ASSAM", "BIHAR", "CHHATTISGARH",
  "GOA", "GUJARAT", "HARYANA", "HIMACHAL PRADESH", "JHARKHAND", "KARNATAKA",
  "KERALA", "MADHYA PRADESH", "MAHARASHTRA", "MANIPUR", "MEGHALAYA", "MIZORAM",
  "NAGALAND", "ODISHA", "PUNJAB", "RAJASTHAN", "SIKKIM", "TAMIL NADU",
  "TELANGANA", "TRIPURA", "UTTAR PRADESH", "UTTARAKHAND", "WEST BENGAL"
]

export const STATE_CITIES: Record<string, string[]> = {
  "KARNATAKA": [
    "BENGALURU", "MYSURU", "HUBBALLI", "DHARWAD", "MANGALURU", "BELAGAVI", 
    "KALABURAGI", "DAVANAGERE", "BALLARI", "VIJAYAPURA", "SHIVAMOGGA", 
    "TUMAKURU", "RAICHUR", "BIDAR", "HASSAN", "GADAG", "UDUPI", "BAGALKOT", 
    "MANDYA", "CHIKKAMAGALURU", "KOPPAL", "CHITRADURGA", "RAMANAGARA", 
    "CHIKKABALLAPURA", "YADGIR", "KOLAR", "CHAMARAJANAGAR", "KODAGU", 
    "DAKSHINA KANNADA", "UTTARA KANNADA"
  ],
  "MAHARASHTRA": [
    "MUMBAI", "PUNE", "NAGPUR", "NASHIK", "AURANGABAD", "SOLAPUR", "AMRAVATI",
    "NANDED", "KOLHAPUR", "AKOLA", "LATUR", "DHULE", "AHMEDNAGAR", "CHANDRAPUR",
    "PARBHANI", "JALGAON", "BHIWANDI", "NAVI MUMBAI", "SANGLI", "MALEGAON"
  ],
  "TAMIL NADU": [
    "CHENNAI", "COIMBATORE", "MADURAI", "TIRUCHIRAPPALLI", "SALEM", "TIRUNELVELI",
    "TIRUPUR", "VELLORE", "ERODE", "THOOTHUKKUDI", "DINDIGUL", "THANJAVUR",
    "RANIPET", "SIVAKASI", "KARUR", "UDHAGAMANDALAM", "HOSUR", "NAGERCOIL",
    "KANCHIPURAM", "CUDDALORE"
  ],
  "TELANGANA": [
    "HYDERABAD", "WARANGAL", "NIZAMABAD", "KHAMMAM", "KARIMNAGAR", "RAMAGUNDAM",
    "MAHBUBNAGAR", "NALGONDA", "ADILABAD", "SURYAPET", "MIRYALAGUDA", "JAGTIAL",
    "MANCHERIAL", "SIDDIPET", "SANGAREDDY", "MEDAK", "VIKARABAD", "WANAPARTHY"
  ],
  "KERALA": [
    "THIRUVANANTHAPURAM", "KOCHI", "KOZHIKODE", "KOLLAM", "THRISSUR", "KANNUR",
    "PALAKKAD", "KOTTAYAM", "MALAPPURAM", "ALAPPUZHA", "PATHANAMTHITTA", 
    "IDUKKI", "KASARAGOD", "WAYANAD"
  ],
  "GUJARAT": [
    "AHMEDABAD", "SURAT", "VADODARA", "RAJKOT", "BHAVNAGAR", "JAMNAGAR",
    "GANDHINAGAR", "JUNAGADH", "GANDHIDHAM", "ANAND", "NAVSARI", "MORBI",
    "MAHESANA", "BHARUCH", "VAPI", "VALSAD", "PALANPUR", "PORBANDAR"
  ],
  "RAJASTHAN": [
    "JAIPUR", "JODHPUR", "UDAIPUR", "KOTA", "BIKANER", "AJMER", "BHILWARA",
    "ALWAR", "BHARATPUR", "SIKAR", "PALI", "TONK", "KISHANGARH", "BEAWAR",
    "HANUMANGARH", "GANGAPUR", "CHURU", "JHUNJHUNU"
  ],
  "WEST BENGAL": [
    "KOLKATA", "HOWRAH", "DURGAPUR", "ASANSOL", "SILIGURI", "BARDHAMAN",
    "MALDA", "BAHARAMPUR", "HABRA", "KHARAGPUR", "SHANTIPUR", "DANKUNI",
    "DHULIAN", "RANAGHAT", "HALDIA", "RAIGANJ", "KRISHNANAGAR", "NABADWIP"
  ],
  "UTTAR PRADESH": [
    "LUCKNOW", "KANPUR", "GHAZIABAD", "AGRA", "VARANASI", "MEERUT", "PRAYAGRAJ",
    "BAREILLY", "ALIGARH", "MORADABAD", "SAHARANPUR", "GORAKHPUR", "NOIDA",
    "FIROZABAD", "JHANSI", "MUZAFFARNAGAR", "MATHURA", "RAMPUR", "SHAHJAHANPUR"
  ],
  "MADHYA PRADESH": [
    "BHOPAL", "INDORE", "GWALIOR", "JABALPUR", "UJJAIN", "SAGAR", "DEWAS",
    "SATNA", "RATLAM", "REWA", "MURWARA", "SINGRAULI", "BURHANPUR", "KHANDWA",
    "BHIND", "CHHINDWARA", "GUNA", "SHIVPURI"
  ],
  "HARYANA": [
    "FARIDABAD", "GURGAON", "PANIPAT", "AMBALA", "YAMUNANAGAR", "ROHTAK",
    "HISAR", "KARNAL", "SONIPAT", "PANCHKULA", "BHIWANI", "SIRSA", "BAHADURGARH",
    "JIND", "THANESAR", "KAITHAL", "PALWAL", "REWARI"
  ],
  "PUNJAB": [
    "LUDHIANA", "AMRITSAR", "JALANDHAR", "PATIALA", "BATHINDA", "MOHALI",
    "FIROZPUR", "BATALA", "PATHANKOT", "MOGA", "ABOHAR", "MALERKOTLA",
    "KHANNA", "PHAGWARA", "MUKTSAR", "BARNALA", "RAJPURA", "HOSHIARPUR"
  ],
  "BIHAR": [
    "PATNA", "GAYA", "BHAGALPUR", "MUZAFFARPUR", "PURNIA", "DARBHANGA",
    "BIHAR SHARIF", "ARRAH", "BEGUSARAI", "KATIHAR", "MUNGER", "CHHAPRA",
    "DANAPUR", "SAHARSA", "HAJIPUR", "SASARAM", "DEHRI", "SIWAN"
  ],
  "ODISHA": [
    "BHUBANESWAR", "CUTTACK", "ROURKELA", "BERHAMPUR", "SAMBALPUR", "PURI",
    "BALASORE", "BHADRAK", "BARIPADA", "JHARSUGUDA", "JEYPORE", "BARBIL",
    "KHORDHA", "BALANGIR", "RAYAGADA", "KORAPUT", "DHENKANAL", "KENDUJHAR"
  ],
  "ASSAM": [
    "GUWAHATI", "SILCHAR", "DIBRUGARH", "JORHAT", "NAGAON", "TINSUKIA",
    "TEZPUR", "BONGAIGAON", "DHUBRI", "DIPHU", "NORTH LAKHIMPUR", "KARIMGANJ",
    "SIBSAGAR", "GOALPARA", "BARPETA", "MANGALDOI", "NALBARI", "RANGIA"
  ],
  "JHARKHAND": [
    "RANCHI", "JAMSHEDPUR", "DHANBAD", "BOKARO", "DEOGHAR", "PHUSRO",
    "HAZARIBAGH", "GIRIDIH", "RAMGARH", "MEDININAGAR", "CHIRKUNDA", "PAKAUR",
    "CHAIBASA", "DUMKA", "SAHIBGANJ", "GUMLA", "MIHIJAM", "CHATRA"
  ],
  "HIMACHAL PRADESH": [
    "SHIMLA", "DHARAMSHALA", "SOLAN", "MANDI", "PALAMPUR", "BADDI", "NAHAN",
    "PAONTA SAHIB", "SUNDARNAGAR", "CHAMBA", "UNA", "KULLU", "HAMIRPUR",
    "BILASPUR", "KANGRA", "NURPUR", "MANALI", "KEYLONG"
  ],
  "UTTARAKHAND": [
    "DEHRADUN", "HARIDWAR", "ROORKEE", "HALDWANI", "RUDRAPUR", "KASHIPUR",
    "RISHIKESH", "KOTDWAR", "RAMNAGAR", "PITHORAGARH", "JASPUR", "KICHHA",
    "MUSSOORIE", "NAINITAL", "ALMORA", "PAURI", "TEHRI", "CHAMOLI"
  ],
  "CHHATTISGARH": [
    "RAIPUR", "BHILAI", "KORBA", "BILASPUR", "DURG", "RAJNANDGAON", "JAGDALPUR",
    "RAIGARH", "AMBIKAPUR", "MAHASAMUND", "DHAMTARI", "CHIRMIRI", "BHATAPARA",
    "DALLI-RAJHARA", "NAILA JANJGIR", "TILDA NEWRA", "MUNGELI", "MANENDRAGARH"
  ],
  "GOA": [
    "PANAJI", "MARGAO", "VASCO DA GAMA", "MAPUSA", "PONDA", "BICHOLIM",
    "CURCHOREM", "SANQUELIM", "CUNCOLIM", "CANACONA", "QUEPEM", "SANGUEM",
    "VALPOI", "PERNEM", "ALDONA", "CORTALIM", "CHINCHINIM", "ARAMBOL"
  ],
  "ANDHRA PRADESH": [
    "VISAKHAPATNAM", "VIJAYAWADA", "GUNTUR", "NELLORE", "KURNOOL", "RAJAHMUNDRY",
    "TIRUPATI", "KADAPA", "KAKINADA", "ANANTAPUR", "VIZIANAGARAM", "ELURU",
    "ONGOLE", "NANDYAL", "MACHILIPATNAM", "ADONI", "TENALI", "CHITTOOR"
  ],
  "ARUNACHAL PRADESH": [
    "ITANAGAR", "NAHARLAGUN", "PASIGHAT", "NAMSAI", "BOMDILA", "TAWANG",
    "ZIRO", "BASAR", "KHONSA", "TEZU", "SEPPA", "ALONG", "CHANGLANG", "ROING"
  ],
  "MANIPUR": [
    "IMPHAL", "THOUBAL", "BISHNUPUR", "CHURACHANDPUR", "UKHRUL", "SENAPATI",
    "TAMENGLONG", "CHANDEL", "JIRIBAM", "KAKCHING", "TENGNOUPAL", "KAMJONG",
    "NONEY", "PHERZAWL", "KANGPOKPI"
  ],
  "MEGHALAYA": [
    "SHILLONG", "TURA", "JOWAI", "NONGPOH", "BAGHMARA", "WILLIAMNAGAR",
    "NONGSTOIN", "MAWKYRWAT", "RESUBELPARA", "AMPATI", "MAIRANG", "KHLIEHRIAT"
  ],
  "MIZORAM": [
    "AIZAWL", "LUNGLEI", "SAIHA", "CHAMPHAI", "KOLASIB", "SERCHHIP", "MAMIT",
    "LAWNGTLAI", "SAITUAL", "KHAWZAWL", "HNAHTHIAL"
  ],
  "NAGALAND": [
    "KOHIMA", "DIMAPUR", "MOKOKCHUNG", "TUENSANG", "WOKHA", "ZUNHEBOTO",
    "PHEK", "KIPHIRE", "LONGLENG", "PEREN", "MON"
  ],
  "SIKKIM": [
    "GANGTOK", "NAMCHI", "GEYZING", "MANGAN", "JORETHANG", "NAYABAZAR",
    "SINGTAM", "RANGPO"
  ],
  "TRIPURA": [
    "AGARTALA", "DHARMANAGAR", "UDAIPUR", "KAILASAHAR", "BELONIA", "KHOWAI",
    "PRATAPGARH", "RANIR BAZAR", "SONAMURA", "KUMARGHAT", "RANIRBAZAR",
    "TELIAMURA", "SABROOM", "BISHALGARH", "MELAGHAR", "MOHANPUR", "KAMALPUR",
    "JIRANIA", "BISRAMGANJ", "ROUTHKHOLA", "PANISAGAR", "AMARPUR", "JAMPUI HILLS",
    "GANDACHERRA"
  ]
}

export const DISTRICTS_BY_STATE: Record<string, string[]> = {
  "KARNATAKA": [
    "BAGALKOT", "BALLARI", "BELAGAVI", "BENGALURU RURAL", "BENGALURU URBAN",
    "BIDAR", "CHAMARAJANAGAR", "CHIKKABALLAPURA", "CHIKKAMAGALURU", "CHITRADURGA",
    "DAKSHINA KANNADA", "DAVANAGERE", "DHARWAD", "GADAG", "HASSAN", "HAVERI",
    "KALABURAGI", "KODAGU", "KOLAR", "KOPPAL", "MANDYA", "MYSURU", "RAICHUR",
    "RAMANAGARA", "SHIVAMOGGA", "TUMAKURU", "UDUPI", "UTTARA KANNADA",
    "VIJAYAPURA", "YADGIR"
  ],
  "MAHARASHTRA": [
    "AHMEDNAGAR", "AKOLA", "AMRAVATI", "AURANGABAD", "BEED", "BHANDARA",
    "BULDHANA", "CHANDRAPUR", "DHULE", "GADCHIROLI", "GONDIA", "HINGOLI",
    "JALGAON", "JALNA", "KOLHAPUR", "LATUR", "MUMBAI CITY", "MUMBAI SUBURBAN",
    "NAGPUR", "NANDED", "NANDURBAR", "NASHIK", "OSMANABAD", "PALGHAR",
    "PARBHANI", "PUNE", "RAIGAD", "RATNAGIRI", "SANGLI", "SATARA", "SINDHUDURG",
    "SOLAPUR", "THANE", "WARDHA", "WASHIM", "YAVATMAL"
  ],
  "TAMIL NADU": [
    "ARIYALUR", "CHENGALPATTU", "CHENNAI", "COIMBATORE", "CUDDALORE", "DHARMAPURI",
    "DINDIGUL", "ERODE", "KALLAKURICHI", "KANCHIPURAM", "KANYAKUMARI", "KARUR",
    "KRISHNAGIRI", "MADURAI", "MAYILADUTHURAI", "NAGAPATTINAM", "NAMAKKAL",
    "NILGIRIS", "PERAMBALUR", "PUDUKKOTTAI", "RAMANATHAPURAM", "RANIPET",
    "SALEM", "SIVAGANGA", "TENKASI", "THANJAVUR", "THENI", "THOOTHUKUDI",
    "TIRUCHIRAPPALLI", "TIRUNELVELI", "TIRUPATTUR", "TIRUPPUR", "TIRUVALLUR",
    "TIRUVANNAMALAI", "TIRUVARUR", "VELLORE", "VILUPPURAM", "VIRUDHUNAGAR"
  ],
  "TELANGANA": [
    "ADILABAD", "BHADRADRI KOTHAGUDEM", "HYDERABAD", "JAGTIAL", "JANGAON",
    "JAYASHANKAR BHUPALPALLY", "JOGULAMBA GADWAL", "KAMAREDDY", "KARIMNAGAR",
    "KHAMMAM", "KUMURAM BHEEM", "MAHABUBABAD", "MAHABUBNAGAR", "MANCHERIAL",
    "MEDAK", "MEDCHAL MALKAJGIRI", "MULUGU", "NAGARKURNOOL", "NALGONDA",
    "NARAYANPET", "NIRMAL", "NIZAMABAD", "PEDDAPALLI", "RAJANNA SIRCILLA",
    "RANGAREDDY", "SANGAREDDY", "SIDDIPET", "SURYAPET", "VIKARABAD",
    "WANAPARTHY", "WARANGAL RURAL", "WARANGAL URBAN", "YADADRI BHUVANAGIRI"
  ],
  "KERALA": [
    "ALAPPUZHA", "ERNAKULAM", "IDUKKI", "KANNUR", "KASARAGOD", "KOLLAM",
    "KOTTAYAM", "KOZHIKODE", "MALAPPURAM", "PALAKKAD", "PATHANAMTHITTA",
    "THIRUVANANTHAPURAM", "THRISSUR", "WAYANAD"
  ],
  "GUJARAT": [
    "AHMEDABAD", "AMRELI", "ANAND", "ARAVALLI", "BANASKANTHA", "BHARUCH",
    "BHAVNAGAR", "BOTAD", "CHHOTA UDEPUR", "DAHOD", "DANG", "DEVBHOOMI DWARKA",
    "GANDHINAGAR", "GIR SOMNATH", "JAMNAGAR", "JUNAGADH", "KHEDA", "KUTCH",
    "MAHISAGAR", "MEHSANA", "MORBI", "NARMADA", "NAVSARI", "PANCHMAHAL",
    "PATAN", "PORBANDAR", "RAJKOT", "SABARKANTHA", "SURAT", "SURENDRANAGAR",
    "TAPI", "VADODARA", "VALSAD"
  ],
  "RAJASTHAN": [
    "AJMER", "ALWAR", "BANSWARA", "BARAN", "BARMER", "BHARATPUR", "BHILWARA",
    "BIKANER", "BUNDI", "CHITTORGARH", "CHURU", "DAUSA", "DHOLPUR", "DUNGARPUR",
    "HANUMANGARH", "JAIPUR", "JAISALMER", "JALORE", "JHALAWAR", "JHUNJHUNU",
    "JODHPUR", "KARAULI", "KOTA", "NAGAUR", "PALI", "PRATAPGARH", "RAJSAMAND",
    "SAWAI MADHOPUR", "SIKAR", "SIROHI", "SRI GANGANAGAR", "TONK", "UDAIPUR"
  ],
  "WEST BENGAL": [
    "ALIPURDUAR", "BANKURA", "BIRBHUM", "COOCH BEHAR", "DAKSHIN DINAJPUR",
    "DARJEELING", "HOOGHLY", "HOWRAH", "JALPAIGURI", "JHARGRAM", "KALIMPONG",
    "KOLKATA", "MALDA", "MURSHIDABAD", "NADIA", "NORTH 24 PARGANAS",
    "PASCHIM BARDHAMAN", "PASCHIM MEDINIPUR", "PURBA BARDHAMAN",
    "PURBA MEDINIPUR", "PURULIA", "SOUTH 24 PARGANAS", "UTTAR DINAJPUR"
  ],
  "UTTAR PRADESH": [
    "AGRA", "ALIGARH", "AMBEDKAR NAGAR", "AMETHI", "AMROHA", "AURAIYA",
    "AYODHYA", "AZAMGARH", "BAGHPAT", "BAHRAICH", "BALLIA", "BALRAMPUR",
    "BANDA", "BARABANKI", "BAREILLY", "BASTI", "BHADOHI", "BIJNOR", "BUDAUN",
    "BULANDSHAHR", "CHANDAULI", "CHITRAKOOT", "DEORIA", "ETAH", "ETAWAH",
    "FARRUKHABAD", "FATEHPUR", "FIROZABAD", "GAUTAM BUDDHA NAGAR", "GHAZIABAD",
    "GHAZIPUR", "GONDA", "GORAKHPUR", "HAMIRPUR", "HAPUR", "HARDOI",
    "HATHRAS", "JALAUN", "JAUNPUR", "JHANSI", "KANNAUJ", "KANPUR DEHAT",
    "KANPUR NAGAR", "KASGANJ", "KAUSHAMBI", "KHERI", "KUSHINAGAR",
    "LALITPUR", "LUCKNOW", "MAHARAJGANJ", "MAHOBA", "MAINPURI", "MATHURA",
    "MAU", "MEERUT", "MIRZAPUR", "MORADABAD", "MUZAFFARNAGAR", "PILIBHIT",
    "PRATAPGARH", "PRAYAGRAJ", "RAE BARELI", "RAMPUR", "SAHARANPUR",
    "SAMBHAL", "SANT KABIR NAGAR", "SHAHJAHANPUR", "SHAMLI", "SHRAVASTI",
    "SIDDHARTHNAGAR", "SITAPUR", "SONBHADRA", "SULTANPUR", "UNNAO", "VARANASI"
  ],
  "MADHYA PRADESH": [
    "AGAR MALWA", "ALIRAJPUR", "ANUPPUR", "ASHOKNAGAR", "BALAGHAT", "BARWANI",
    "BETUL", "BHIND", "BHOPAL", "BURHANPUR", "CHACHAURA", "CHHATARPUR",
    "CHHINDWARA", "DAMOH", "DATIA", "DEWAS", "DHAR", "DINDORI", "GUNA",
    "GWALIOR", "HARDA", "HOSHANGABAD", "INDORE", "JABALPUR", "JHABUA",
    "KATNI", "KHANDWA", "KHARGONE", "MAIHAR", "MANDLA", "MANDSAUR", "MORENA",
    "NARSINGHPUR", "NEEMUCH", "NIWARI", "PANNA", "RAISEN", "RAJGARH",
    "RATLAM", "REWA", "SAGAR", "SATNA", "SEHORE", "SEONI", "SHAHDOL",
    "SHAJAPUR", "SHEOPUR", "SHIVPURI", "SIDHI", "SINGRAULI", "TIKAMGARH",
    "UJJAIN", "UMARIA", "VIDISHA"
  ]
  // Add more states as needed for comprehensive coverage
}

export const ENGINEERING_BRANCHES = [
  { value: "CSE", label: "Computer Science and Engineering" },
  { value: "ISE", label: "Information Science and Engineering" },
  { value: "ECE", label: "Electronics and Communication Engineering" },
  { value: "EEE", label: "Electrical and Electronics Engineering" },
  { value: "ME", label: "Mechanical Engineering" },
  { value: "CE", label: "Civil Engineering" },
  { value: "AIML", label: "Artificial Intelligence and Machine Learning" },
  { value: "DS", label: "Data Science" }
]

export const SEAT_CATEGORIES = [
  { value: "KCET", label: "KCET (Karnataka CET)" },
  { value: "MANAGEMENT", label: "Management Quota" },
  { value: "COMEDK", label: "COMEDK" }
]

export const TRANSPORT_MODES = [
  { value: "COLLEGE_BUS", label: "College Bus" },
  { value: "PRIVATE_TRANSPORT", label: "Private Transport" },
  { value: "PUBLIC_TRANSPORT", label: "Public Transport" },
  { value: "WALKING", label: "Walking" }
]

export const BOARDS = [
  { value: "STATE", label: "State Board" },
  { value: "CBSE", label: "CBSE" },
  { value: "ICSE", label: "ICSE" }
]

export const MARKS_TYPES = [
  { value: "PERCENTAGE", label: "Percentage" },
  { value: "SUBJECTS_TOTAL", label: "Subjects with Total Marks" },
  { value: "OUT_OF_1000", label: "Marks out of 1000" }
]

export const MONTHS = [
  { value: 1, label: "January" },
  { value: 2, label: "February" },
  { value: 3, label: "March" },
  { value: 4, label: "April" },
  { value: 5, label: "May" },
  { value: 6, label: "June" },
  { value: 7, label: "July" },
  { value: 8, label: "August" },
  { value: 9, label: "September" },
  { value: 10, label: "October" },
  { value: 11, label: "November" },
  { value: 12, label: "December" }
]
